#!/bin/sh
# TODO: Distinguish between Linux distros
system=`uname -s`

# Run the system-specific installer script
progdir=`dirname "$0"`
case $system in
Darwin)
    sh -x "$progdir/macos.sh" ;;
*)  echo >&2 "Unsupported system: $system"
    exit 1 ;;
esac
